# SPDX-License-Identifier: MIT
linters:
  disable-all: true
  fast: false
  enable:
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - godox
    - govet
    - gosec
    - gosimple
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cloudbase/garm)

  goimports:
    local-prefixes: github.com/cloudbase/garm

  gosec:
    excludes:
    - G115
