# NOTE: The purpose of these definitions is to reuse the existing golang
# types from GARM packages.
definitions:
  Instances:
    type: object
    x-go-type:
        type: Instances
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  Instance:
    type: object
    x-go-type:
        type: Instance
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  Pools:
    type: object
    x-go-type:
        type: Pools
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  Pool:
    type: object
    x-go-type:
        type: Pool
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  Repositories:
    type: array
    x-go-type:
        type: Repositories
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
    items:
        $ref: '#/definitions/Repository'
  Repository:
    type: object
    x-go-type:
        type: Repository
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  CreateRepoParams:
    type: object
    x-go-type:
        type: CreateRepoParams
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  UpdateEntityParams:
    type: object
    x-go-type:
        type: UpdateEntityParams
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  CreatePoolParams:
    type: object
    x-go-type:
        type: CreatePoolParams
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  UpdatePoolParams:
    type: object
    x-go-type:
        type: UpdatePoolParams
        import:
            package: github.com/cloudbase/garm/params
            alias: garm_params
  APIErrorResponse:
    type: object
    x-go-type:
        type: APIErrorResponse
        import:
            package: github.com/cloudbase/garm/apiserver/params
            alias: apiserver_params
